billing component created
Lambda-School-Labs/labspt2-ksl-alerts pull request #21
Opened 2019-03-16 22:05 UTC by marcusbass323

Billing component up w/ semantic-ui and styled-components.

Need to add box-shadow properties.
Needs form validation.
Would like to add hide/unhide toggle fields via state.

2019-03-18 19:30 UTC, belzy approved these changes

2019-03-18 21:07 UTC, kiadorii commented
Merge conflict present

2019-03-26 23:37 UTC, kiachoi requested changes
Merge conflict error: createAlert.js
Please get this resolved asap

2019-03-26 23:37 UTC, kiadorii commented on client/src/components/Billing/Billing.js
> +import React, { Component } from "react";
Would highly encourage you to format this page before pushing it through.

2019-03-29 04:11 UTC, closed without merging